# containers section defines what containers to build
containers:
  basic:
    opencfd-openfoam:
      os:
        distro: ubuntu
        version: 24.04
      mpi:
        implementation: openmpi
        version: 4.1.5
      framework:
        definition: com-openfoam
        version: 2312
        git_ref: OpenFOAM-v2312 # optional (default: default)
  projects:
    # you get test-master.sif and test-dev.sif from the following entry
    solver:
      base_container: opencfd-openfoam # what base container to build the project against (from containers.basic above)
      definition: defs/solver-OpenFOAM-v2312.def # path to container definition file (relative to CWD)
      build_args: # case-insensitive, optional build arguments for apptainer
        branch:
          - master  # will be passed as `--build-arg BRANCH=master` to `apptainer build`


pull:
  try_to_pull: false # Do we try to pull from registry?
  protocol: "oras" # docker, or library as Pull protocol
  scope: "ghcr.io/foamscience" # so oras://ghcr.io/foamscience/<container-name>:latest is used
